### ISSUE TITLE
Create "base-maven" image

### ISSUE THREAD

**Issue by ALRubinger** [jboss-dockerfiles/base-maven#1]

**Comment by ALRubinger** [comment]
@goldmann @l-d-j Does this now get auto-built and pushed to Docker Hub, or should I/we set up that infra?

**Comment by goldmann** [comment]
It needs to be set up by me, I'll do it tomorrow.

**Comment by ALRubinger** [comment]
@goldmann You really know how to party on the weekend, man.

**Comment by goldmann** [comment]
And while being on PTO ;)

**Comment by ALRubinger** [comment]
NERD ALERT. :laughing:

**Comment by goldmann** [comment]
Done! https://hub.docker.com/r/jboss/base-maven/

New image will be built once a new commit will be pushed to master (it'll end up with `latest` tag) or when repository will be tagged (it'll tag the image with the pushed tag).
